name: tobeto_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  dotted_decoration: ^2.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.4.9
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.6.0
  lottie: ^2.7.0
  another_flutter_splash_screen: ^1.2.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_database: ^10.4.0
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.14.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  meta: ^1.9.1
  fluttertoast: ^8.2.4
  dropdown_model_list: ^2.0.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  art_sweetalert: ^0.0.5
  country_code_picker: ^3.0.0
  google_sign_in: ^6.1.6
  syncfusion_flutter_calendar: ^22.2.12
  timeline_tile: ^2.0.0
  path_provider: ^2.1.2
  file_picker: ^6.1.1
    
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
    - "assets/images/profile_screen/"
    - "assets/images/home_screen/"
    - "assets/animations/"

  fonts:
    - family: "Tinos" 
      fonts:
        - asset: 'assets/fonts/Tinos-Bold.ttf'
        - asset: 'assets/fonts/Tinos-BoldItalic.ttf'
        - asset: 'assets/fonts/Tinos-Italic.ttf'
        - asset: 'assets/fonts/Tinos-Regular.ttf'
