name: tobeto_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  another_flutter_splash_screen: ^1.2.0
  dotted_decoration: ^2.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.6.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
    - "assets/images/profile_screen/"
    - "assets/animations/"

  fonts:
    - family: "Tinos" 
      fonts:
        - asset: 'assets/fonts/Tinos-Bold.ttf'
        - asset: 'assets/fonts/Tinos-BoldItalic.ttf'
        - asset: 'assets/fonts/Tinos-Italic.ttf'
        - asset: 'assets/fonts/Tinos-Regular.ttf'
