name: tobeto_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"

  fonts:
    - family: "Tinos" 
      fonts:
        - asset: 'assets/fonts/Tinos-Bold.ttf'
        - asset: 'assets/fonts/Tinos-BoldItalic.ttf'
        - asset: 'assets/fonts/Tinos-Italic.ttf'
        - asset: 'assets/fonts/Tinos-Regular.ttf'
